language: node_js
node_js:
- "10"
services:
- docker
before_install:
# install heroku CLI
- npm run ci:up
install:
- npm install
test:
- npm run test:ci
after_script:
- npm run ci:down	
on:
branch: master