language: node_js
node_js:
- "10"
services:
- docker
before_install:
- npm run ci:up
- docker build -t service-matteoaffinity .
test:
- docker run -d -p 4000:4000 service-matteoaffinity 
- docker exec service-matteoaffinity sh -c "npm run test:ci"
after_script:
- npm run ci:down	
- docker stop service-matteoaffinity
on:
branch: master