language: node_js
node_js:
- "10"
services:
- docker
install:
- echo "skip install"
before_script:
- npm run ci:up
- sleep 2
script:
- echo "pre test"
- docker exec -it service-matteoaffinity npm run test:ci
after_script:
- npm run ci:down
on:
branch: master