language: node_js
node_js:
- "10"
services:
- docker
install:
- echo "skip install"
before_script:
- npm run ci:up
- sleep 2
script:
- echo "pre test"
- docker exec -it service-matteoaffinity npm run test:ci
after_script:
- npm run ci:down
deploy:
provider: script
script: echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com; heroku container:push web -a $APP_NAME; heroku container:release web -a $APP_NAME;
on:
branch: master